"""empty message

Revision ID: 3672d83e2bb2
Revises: 8f3e86803e43
Create Date: 2018-02-12 22:45:36.318341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3672d83e2bb2'
down_revision = '8f3e86803e43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Images', sa.Column('position', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Images', 'position')
    # ### end Alembic commands ###
